# Generated by Django 2.0.6 on 2018-06-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbNail',
            field=models.ImageField(blank=True, default='defaultImg.png', upload_to=''),
        ),
    ]
